export const API_ENDPOINT = {
  LOGIN: "/auth/login",
  GET_ALL_PRODUCTS: "/product/",
  CREATE_PRODUCT: "/product/",
  UPLOAD_SKETCH_PRODUCT: "/product/image/denah/upload/",
  UPLOAD_IMAGES_PRODUCT: "/product/image/slide/upload/",
  DELETE_PRODUCT: "/product/",
  GET_ALL_USERS: "/user/",
  CREATE_USER: "/user/",
  UPDATE_USER: "/user/",
  DELETE_USER: "/user/",
  GET_BLOG: "/blog",
  POST_BLOG: "/blog",
  PATCH_BLOG: "/blog",
  DELETE_BLOG: "/blog",
  POST_IMAGE_BLOG: "/blog/image/upload/",
};
